/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const InfinityLazyImport = createFileRoute('/infinity')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const InfinityLazyRoute = InfinityLazyImport.update({
  id: '/infinity',
  path: '/infinity',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/infinity.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/infinity': {
      id: '/infinity'
      path: '/infinity'
      fullPath: '/infinity'
      preLoaderRoute: typeof InfinityLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/infinity': typeof InfinityLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/infinity': typeof InfinityLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/infinity': typeof InfinityLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/infinity'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/infinity'
  id: '__root__' | '/' | '/infinity'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  InfinityLazyRoute: typeof InfinityLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  InfinityLazyRoute: InfinityLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/infinity"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/infinity": {
      "filePath": "infinity.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
